language: python
python:
  - "3.8"  

cache: pip

install:
  - pip install -r requirements.txt  


after_script:
  - coveralls

script:
  - black --check .  
  - flake8 --exclude=migrations.
  - coverage run --source=pollsite,polls manage.py test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWSACCESSKEYID
  secret_access_key: $SECRETACCESSKEYID
  region: "us-west-2"
  app: "qasite"
  env: "qasite-env"
  bucket_name: "elasticbeanstalk-us-west-2-004692833247"
  bucket_path: "qasite/"
  on:
    branch: main
  
