language: python
python:
  - "3.8"  

cache: pip

install:
  - pip install -r requirements.txt  


after_script:
  - coveralls



script:
  - black --check .  
  - flake8 .
  - coverage run --source=mysite,polls manage.py test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWSACCESSKEYID
  secret_access_key:
    secure: $SECRETACCESSKEYID
  region: "us-west-2"
  app: "eqasite"
  env: "qasite-env"
  bucket_name: "s3://elasticbeanstalk-us-west-2-004692833247/qasite/"
  
