language: python
python:
  - "3.8"  

cache: pip

services:
  - sqlite

install:
  - pip install -r requirements.txt  
  # - pip install python==3.8

before_script:
  - python manage.py migrate

after_script:
  - coveralls

script:
  - black --check .  
  - flake8 .
  - coverage run --source=mysite,polls manage.py test